name             'dt_opsworks'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures dt_opsworks'
long_description 'Installs/Configures dt_opsworks'
version          '0.1.0'

depends 'deploy'
depends 'varnish'
